### ISSUE TITLE
Displaced error cropped boundingbox

### ISSUE THREAD

**Issue by MrMJ06** [sentinel-hub/eo-learn#152] opened 2019-10-10 15:21 UTC
Hello eo-learn team, 
first of all thank you for your amazing library and your work.

We have made a comparative between the tile downloaded from sentinelhub and the cropped boundingbox and we have seen a displacement in the images in the x and y axes.

![Screenshot from 2019-10-10 17-19-24](https://user-images.githubusercontent.com/26347446/66582489-2fb24980-eb82-11e9-947b-282f2f67be05.png)

We don't know if you are aware of this or is a problem from any of the libraries used in eo-learn.

We are waiting for your response, 
thank you very much and regards.

**Comment by devisperessutti** [comment] 2019-11-20 09:26
HI @MrMJ06,

Can you please provide a code snippet to reproduce your findings?

More context would be helpful to pinpoint the issue.

Thanks

**Comment by mlubej** [comment] 2020-06-17 13:35
Closing this since no additional data was provided. Will reopen the issue if @MrMJ06 provides the helpful info to investigate.

**Closed by mlubej** 2020-06-17 13:35 UTC
