### ISSUE TITLE
Some examples given in the repo are not working

### ISSUE THREAD

**Issue by bashwizard** [sentinel-hub/eo-learn#231] opened 2020-07-21 05:23 UTC
As I am completely new to EO, have been trying to go through all the examples one by one. Here are some that aren't working:

1. eo-learn/examples/features/RadiometricNormalisation.ipynb

NameError: During execution of task ValidDataCoverageTask: name 'valid_fraction' is not defined

I think the reason is that during method definition

class ValidDataCoverageTask(EOTask):
    def execute(self, eopatch):
        _**frac = np.apply_along_axis(valid_fraction, 1, np.reshape(vld, (vld.shape[0], -1)))**_

valid_fraction is not defined anywhere.

2. eo-learn/examples/io/RequestDataComparison.ipynb

error: DownloadFailedException: Failed to download from
400 Client Error: Bad Request for url
Server response: "TYPENAME=DSS2 not found!"

Possibly some url is changed?

3. eo-learn/examples/land-cover-fastai/deep_lulc_walkthrough.ipynb

DriverError: ../../example_data/svn_buffered.geojson: No such file or directory

The file is not present in the repo. There was another country file there which I used instead (svn_border.geojson) but then I ended up on another error

AttributeError: 'GeometryArray' object has no attribute 'tolist'
---> 21     aoi_shape = aoi_reprj.geometry.values.tolist()[-1]

I have seen this before as well. Not sure if I am doing something wrong. 

4. eo-learn/examples/poverty-detection-keras/Poverty_Detection_Workflow.ipynb

DriverError: /Users/ambujtiwari/eo-learn/examples/poverty-detection-keras/geopolygons/super_small_rwanda_aoi.geojson: No such file or directory

geopolygons folder is missing in the repo

5. eo-learn/examples/social-media/DisplayTweets.ipynb

DriverError: twitter_data.geojson: No such file or directory
 
6. eo-learn/examples/tree-cover-keras/tree-cover-keras.ipynb

error: DownloadFailedException: Failed to download from
400 Client Error: Bad Request for url
Server response: "TYPENAME=DSS2 not found!"

Many thanks in advance!

**Comment by devisperessutti** [comment] 2020-07-21 08:59
Hello @bashwizard 

Thank you for reporting this. We will have a look at each notebook and try to fix them accordingly.

**Comment by AleksMat** [comment] 2020-07-21 09:12
Hi @bashwizard, 

I think you are getting this error because you are trying to download Sentinel-2 L2A data but you don't have any layer defined with Sentinel-2 L2A data source in your Sentinel Hub Configurator for your instance id. It's a bit bizarre problem but without a layer, which would use Sentinel-2 L2A data, Sentinel Hub WFS service can't find acquisition dates for it.

**Comment by bashwizard** [comment] 2020-07-22 07:03
Hi @AleksMat
Thanks for the quick reply. Super accurate intuition! Adding another layer with S2-L2A in my Shub configuration solved the issue for eo-learn/examples/tree-cover-keras/tree-cover-keras.ipynb

However, for eo-learn/examples/io/RequestDataComparison.ipynb I got an error while using SentinelHubWCSInput whereas it did work for SentinelHubInputTask. The error for  SentinelHubWCSInput was 
Server response: "Layer BANDS-S2-L2A not found"
but if I understood correctly OGC is being depreciated so the preferred method is SentinelHubInputTask which works!

@AleksMat  @devisperessutti  So my first priority is to solve error 3 in the above list:
AttributeError: 'GeometryArray' object has no attribute 'tolist'
---> 21 aoi_shape = aoi_reprj.geometry.values.tolist()[-1]
Can you please advise on that. After this maybe we can verify if error 4 and 5 are indeed just missing files. Thanks again!

**Comment by mlubej** [comment] 2020-07-22 07:13
Hi @bashwizard 

> AttributeError: 'GeometryArray' object has no attribute 'tolist'
---> 21 aoi_shape = aoi_reprj.geometry.values.tolist()[-1]

It seems that the usage assumes that the `aoi_reprj.geometry` is a numpy array and not a `GeometryArray`. `tolist` is a numpy method, but I think you can just drop it here and use `...values[-1]`.

**Comment by bashwizard** [comment] 2020-07-22 07:29
> AttributeError: 'GeometryArray' object has no attribute 'tolist'
> ---> 21 aoi_shape = aoi_reprj.geometry.values.tolist()[-1]
> 
> I have seen this before as well. Not sure if I am doing something wrong.

@mlubej Thanks, indeed this is what I did at other places to solve the issue. If I do the same here, I am getting another error now:
DriverError: ../../example_data/**land_cover_subset_large**/land_cover_subset_large.shp: No such file or directory
This whole folder land_cover_subset_large is missing.

**Comment by bashwizard** [comment] 2020-07-22 07:31
> 1. eo-learn/examples/features/RadiometricNormalisation.ipynb
> 
> NameError: During execution of task ValidDataCoverageTask: name 'valid_fraction' is not defined
> 
> I think the reason is that during method definition
> 
> class ValidDataCoverageTask(EOTask):
> def execute(self, eopatch):
> _**frac = np.apply_along_axis(valid_fraction, 1, np.reshape(vld, (vld.shape[0], -1)))**_
> 
> valid_fraction is not defined anywhere.

@mlubej This is the only other error which is not caused by a missing file. How should one decide on the value of valid_fraction? Also, is there any old branch of the repo where these missing files can be found? 
Thanks again!

**Comment by mlubej** [comment] 2020-07-22 07:37
> @mlubej Thanks, indeed this is what I did at other places to solve the issue. If I do the same here, I am getting another error now:
DriverError: ../../example_data/land_cover_subset_large/land_cover_subset_large.shp: No such file or directory
This whole folder land_cover_subset_large is missing.

We went through some example refactoring recently, but for some of the examples we decided that they are beyond fixing. 

In any case, in the LULC example the land cover AOI and the reference was changed, so try changing to using the datasets in `eo-learn/example_data`:
- `svn_border.geojson` for the border of the country
- `land_use_10class_reference_slovenia_partial.gpkg` instead of other land cover subsets

> @mlubej This is the only other error which is not caused by a missing file. How should one decide on the value of valid_fraction? Also, is there any old branch of the repo where these missing files can be found?
Thanks again!

This seems to be an issue of the notebook indeed. I guess something went wrong when refactoring it, let me make a fix real quick, sorry.

**Comment by bashwizard** [comment] 2020-07-22 07:48
@mlubej Thanks a lot for getting me started! 

> but for some of the examples we decided that they are beyond fixing.

which one are these? Maybe I should stay away from them!

**Comment by mlubej** [comment] 2020-07-22 08:01
> which one are these? Maybe I should stay away from them!

They should be the ones with a disclaimer warning at the top. If you don't see the note, please update eolearn :)
![image](https://user-images.githubusercontent.com/37869250/88150876-3d612900-cc02-11ea-820f-8ace9f814384.png)

**Comment by mlubej** [comment] 2020-07-22 08:07
> This seems to be an issue of the notebook indeed. I guess something went wrong when refactoring it, let me make a fix real quick, sorry.

Fixed in [latest develop](https://github.com/sentinel-hub/eo-learn/tree/develop/core/eolearn). Thanks again!

**Comment by devisperessutti** [comment] 2020-07-28 14:31
@bashwizard 

To recap using your enumerated list:

 1. was fixed by @mlubej 
 2. and 6. were due to a layer configuration issue
 3. has been fixed in open PR #236 
 5. The README contains information on how to download the Twitter data

The only remaining issue seem to be with missing input files in 4. Poverty_Detection_Workflow.ipynb. Although some data needs to be requested and is not provided with the example, we should add the geometry files @drewbo could you please have a look at this?

**Comment by visalikk** [comment] 2020-07-30 17:22
> > AttributeError: 'GeometryArray' object has no attribute 'tolist'
> > ---> 21 aoi_shape = aoi_reprj.geometry.values.tolist()[-1]
> > I have seen this before as well. Not sure if I am doing something wrong.
> 
> @mlubej Thanks, indeed this is what I did at other places to solve the issue. If I do the same here, I am getting another error now:
> DriverError: ../../example_data/**land_cover_subset_large**/land_cover_subset_large.shp: No such file or directory
> This whole folder land_cover_subset_large is missing.

Yes . Where can we find land_cover_subset_large folder for lulc_mask to work

**Comment by visalikk** [comment] 2020-07-30 17:31
> > @mlubej Thanks, indeed this is what I did at other places to solve the issue. If I do the same here, I am getting another error now:
> > DriverError: ../../example_data/land_cover_subset_large/land_cover_subset_large.shp: No such file or directory
> > This whole folder land_cover_subset_large is missing.
> 
> We went through some example refactoring recently, but for some of the examples we decided that they are beyond fixing.
> 
> In any case, in the LULC example the land cover AOI and the reference was changed, so try changing to using the datasets in `eo-learn/example_data`:
> 
> * `svn_border.geojson` for the border of the country
> * `land_use_10class_reference_slovenia_partial.gpkg` instead of other land cover subsets
> 
> > @mlubej This is the only other error which is not caused by a missing file. How should one decide on the value of valid_fraction? Also, is there any old branch of the repo where these missing files can be found?
> > Thanks again!
> 
> This seems to be an issue of the notebook indeed. I guess something went wrong when refactoring it, let me make a fix real quick, sorry.

@mlubej . If i understand correctly for lulc_mask variable we have to pass land_use_10class_reference_slovenia_partial.gpkg` instead of ' ../../example_data/land_cover_subset_large/land_cover_subset_large.shp' and where to use svn_border.geojson ? Please share exact line and correct me if i am wrong

**Comment by mlubej** [comment] 2020-08-05 09:37
Hi @visalikk,

> Yes . Where can we find land_cover_subset_large folder for lulc_mask to work

There is no `land_cover_subset_large` anymore. You should update the package and use `example_data/land_use_10class_reference_slovenia_partial.gpkg`

**Comment by visalikk** [comment] 2020-08-05 18:37
Hi Matic,
Thanks. Got it. 
As training takes lot of memory and time, could you please share  model_SI_LULC.pkl model file.  Thanks

**Comment by mlubej** [comment] 2020-08-06 07:45
Hi @visalikk,

what are your computer specifications? The training shouldn't take a lot of memory and time, since the notebook was designed to be run on a standard laptop. Perhaps you are hitting some other issues?

In any case, here is the model: [model_SI_LULC.pkl.zip](https://github.com/sentinel-hub/eo-learn/files/5033290/model_SI_LULC.pkl.zip)

**Comment by Geoyi** [comment] 2020-09-14 18:13
@devisperessutti, we have all the data, AOIs as well as the colab notebook for the poverty detection under [a Google Drive](https://drive.google.com/drive/folders/1cE2F_MGu0iRTTWM_guwYDzGVq6n6W4w1?usp=sharing). Do you want me to upload it somewhere else?

**Comment by Ovion** [comment] 2020-09-25 07:39
Hi, I'm completely new to EO too, and I tried tu run an example and deosn't work:

/examples/land-cover-map/SI_LULC_pipeline.ipynb

In cell 3, line 2, during the UtmZoneSplitter an error rise:

```python
bbox_splitter = UtmZoneSplitter([country_shape], country.crs, 5000)
```

ValueError: sentinelhub-py supports only WGS 84 coordinate reference system with coordinate order lng-lat. However pyproj.CRS(4326) has coordinate order lat-lng

I've tried to change the projection of the country but doesn't work. I've also tried to use BBoxSplitter but have the same error.

Many thanks in advance!

**Comment by mlubej** [comment] 2020-09-25 08:12
Hi @Ovion,

are you using some different area in the example? Did you introduce any changes to the notebook?

**Comment by Ovion** [comment] 2020-09-25 14:00
> Hi @Ovion,
> 
> are you using some different area in the example? Did you introduce any changes to the notebook?

Nope, just cloning the repo and then run this example.

**Comment by mlubej** [comment] 2020-09-25 14:03
Weird, it works for me. What are your pip versions of pyproj, geopandas, and sentinelhub?

**Comment by Ovion** [comment] 2020-09-28 06:27
> Weird, it works for me. What are your pip versions of pyproj, geopandas, and sentinelhub?

Yeah, it's weird... I use
pyproj 2.6.1.post1
geopandas 0.8.1
sentinelhub 3.0.5

And the example in master. If it works for you, it must be a own problem...

**Comment by AleksMat** [comment] 2020-09-28 08:52
Hi @Ovion,

For now I recommend doing the following:

```Python
from sentinelhub import CRS

bbox_splitter = UtmZoneSplitter([country_shape], CRS.WGS84, 5000)
```
We'll have a look how we can improve this in the future.

**Comment by Ovion** [comment] 2020-09-28 09:11
> Hi @Ovion,
> 
> For now I recommend doing the following:
> 
> ```python
> from sentinelhub import CRS
> 
> bbox_splitter = UtmZoneSplitter([country_shape], CRS.WGS84, 5000)
> ```
> 
> We'll have a look how we can improve this in the future.

Thanks @AleksMat ! The problem is solved with your answer, but another one appears. But must be my mistake. Thanks a lot I'll try to figure out what happens. And thanks for being aware of these comments!

**Comment by AleksMat** [comment] 2021-05-20 22:06
Closing an old issue as these things shouldn't be a problem anymore.

**Closed by AleksMat** 2021-05-20 22:06 UTC
